version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql-shard1
      - mysql-shard2

  mysql-shard1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql-shard1/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard1-data:/var/lib/mysql

  mysql-shard2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shard2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql-shard2/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-shard2-data:/var/lib/mysql

volumes:
  mysql-shard1-data:
  mysql-shard2-data:
