version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: demo_zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:2.7
    container_name: demo_kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo_kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: demo_kafka:9092
    ports:
      - "9089:8080"
    links:
      - kafka
  kafka-tools:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_tools
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper
    command: ["tail", "-f", "/dev/null"]
  mysql:
    image: mysql:8.0
    container_name: demo_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: inventory
      # MYSQL_USER: "root"
      MYSQL_PASSWORD: root1234
    ports:
      - "30306:3306"
    command:
      --log-bin=mysql-bin --binlog-format=ROW --server-id=1 --gtid-mode=ON --enforce-gtid-consistency=ON
  redis:
    image: redis:7.0
    container_name: demo_redis_container
    ports:
      - "6379:6379"   
  connect:
    image: quay.io/debezium/connect:2.7
    container_name: demo_connect
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses