server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  - job_name: nodejs-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app
          service: nodejs-monitoring-app
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            component: component
            trace_id: trace_id
            duration: duration
            method: method
            url: url
            status: statusCode
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          component:
          method:
          status:
      - output:
          source: message

  # System logs (if available)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          service: system-logs
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<service>\S+):\s+(?P<message>.*)'
      - timestamp:
          source: timestamp
          format: Jan 2 15:04:05
      - labels:
          hostname:
          service:
      - output:
          source: message

  # Docker container logs (if running in Docker)
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            log: log
            stream: stream
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          stream:
      - output:
          source: log

  # Error logs specifically
  - job_name: nodejs-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app-errors
          service: nodejs-monitoring-app
          level: error
          __path__: /var/log/app/error.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            error: error
            stack: stack
            component: component
            trace_id: trace_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          component:
          trace_id:
      - output:
          source: message

  # Combined logs
  - job_name: nodejs-combined-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-app-combined
          service: nodejs-monitoring-app
          __path__: /var/log/app/combined.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            component: component
            method: method
            url: url
            duration: duration
            status: statusCode
            ip: ip
            userAgent: userAgent
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          component:
          method:
          status:
      - output:
          source: message

  # Business events logs
  - job_name: business-events
    static_configs:
      - targets:
          - localhost
        labels:
          job: business-events
          service: nodejs-monitoring-app
          __path__: /var/log/app/business.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event_type: event_type
            user_id: user_id
            order_id: order_id
            amount: amount
            category: category
            details: details
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          event_type:
          category:
      - output:
          source: details
