version: '3.8'

services:
  app:
    container_name: node-app
    build:   # Sử dụng Dockerfile trong cùng thư mục
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - redis
    ports:
      - "3000:3000" # Expose cổng cho server.js
    environment:
      - REDIS_HOST:redis # Tên service 'redis' để kết nối
      - NODE_ENV:development
    networks:
      - app-network
    volumes:
      - ./:/usr/src/app
      - app-data:/usr/src/app/data # Volume để lưu trữ dữ liệu ứng dụng

  redis:
    container_name: node-redis
    image: redis:latest
    ports:
      - "6381:6379" # Ánh xạ port 6380 trên host đến port 6379 trong container
    networks:
      - app-network
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-data:/data # Volume để lưu trữ dữ liệu Redis

# Cấu hình mạng và volume
networks:
  app-network:
    driver: bridge

volumes:
  app-data:
  redis-data:
