version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # WebUI (Console)
    command: server /data --console-address ":9001"
