version: '3.8'

services:
  auth-server:
    build: ./auth-server
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=supersecret

  app-server:
    build: ./app-server
    ports:
      - "3000:3000"
    depends_on:
      - auth-server
